### ISSUE TITLE
Modified files in master after cloning repository

### ISSUE THREAD

**Issue by KruchDmitriy** [eugenyk/hpcourse#179]
Добрый день!

Сразу после клонирования репозитория эти файлы были помечены как *modified*.

```
modified:   leti/1304/mi/1/Matrix.cpp
modified:   leti/1304/mi/1/Matrix.h
modified:   leti/1304/mi/1/main.cpp
```

Насколько я понимаю, проблема связана с line ending'ами в этих файлах.

upd:
Создал пулл реквест с фиксом (#180).

**Comment by eugenyk** [comment]
Спасибо, всё верно
